name: release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          push: true
          tags: loeken/prowlarr:1.33.3.4975
          context: .
          no-cache: true
