name: release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: loeken/prowlarr:1.31.2.4975
          context: .
          no-cache: true
